name: Run feature tests with cucumber

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby 2.7.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true
    
    - name: Setup JVM
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
    
    - name: Download FHIR IG Publisher
      run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O org.hl7.fhir.publisher.jar

    - name: Install Jekyll
      run: gem install jekyll --no-document
    
    - name: Build with FHIR IG Publisher
      run: java -jar org.hl7.fhir.publisher.jar -ig ig.ini
    
    - name: Run cucumber tests
      run: bundle exec cucumber --color
