name: Run feature tests with cucumber

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1

    - name: install gems
      run: bundle install
    
    - name: Setup JVM
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
            
    - name: Download FHIR validator
      run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator.jar
    
    - name: Download FHIR IG Publisher
      run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O publisher.jar
    
    - name: Build with FHIR IG Publisher
      run: java -jar publisher.jar -ig ig.ini
    
    - name: Run cucumber tests
      run: bundle exec cucumber --color --quiet
