name: Run IG Publisher

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
    
    - name: Set up JVM
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Download FHIR IG Publisher
      run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O publisher.jar
    
    - name: Install Jekyll
      run: gem install jekyll --no-document
    
    - name: Build with FHIR IG Publisher
      run: java -jar publisher.jar -ig ig.ini

