name: Validate all FHIR resources against core FHIR spec v4.0.1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup JVM
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
    
    - name: Download FHIR validator
      run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator.jar
    
    # validate StructureDefinition resources, against core FHIRVersion 4.0.1
    - name: Validate StructureDefinition resources, against core FHIRVersion 4.0.1
      run: java -jar validator.jar -version 4.0.1 input/resources/StructureDefinition/*.xml
    
